CREATE DATABASE IF NOT EXISTS parking CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE parking;

CREATE TABLE IF NOT EXISTS slots (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  slot_number   INT NOT NULL UNIQUE,
  is_booked     TINYINT(1) NOT NULL DEFAULT 0,
  booked_by     VARCHAR(100) DEFAULT NULL,
  release_code  VARCHAR(12) DEFAULT NULL,
  booked_at     DATETIME DEFAULT NULL
);

-- Seed slots 1..20. Adjust NUM_SLOTS in .env for new deployments,
-- or insert additional rows manually for existing databases.
INSERT IGNORE INTO slots (slot_number)
SELECT n FROM (
  SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
  UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
  UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS numbers;
